# My TMUX Config

# ZSH as default TMUX shell
set-option -g default-shell /bin/zsh

# 256 term colors
set -g default-terminal "screen-256color"

# set pane-base index
set-option -g base-index 1
set-window-option -g pane-base-index 1
set-window-option -g mouse on

# set scroll-back history
set -g history-limit 10000

# set mouse support
set -g mouse on

# decrease command delay
set -sg escape-time 1

# decrease escape timing for better scroll-buffer response
set -s escape-time 0

# remap prefix key from CTRL-b to CTRL-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using h(horizontal) and v(vertical)
bind v split-window -h -c'#{pane_current_path}'
bind h split-window -v -c'#{pane_current_path}'
unbind '"'
unbind %

# switch panes using ALT-arrow keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Copy bindings. Unbind Ctrl + a, [ to enter copy mode, and
# bind ESCAPE
unbind [
bind Escape copy-mode

# vi mode copy keys
# go to start point, press 'v' and start copying, select with
# arrows
# After text selection, just press 'y' (or the default ‘enter’
# key) to copy text
setw -g mode-keys vi
# Capital 'P' for paste
unbind p
bind P paste-buffer

# silent like a ninja
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

#### COLOUR (Solarized 256)

# default statusbar colors
set-option -g status-style fg=colour136,bg=colour235 #yellow and base02

# default window title colors
set-window-option -g window-status-style fg=colour244,bg=default #base0 and default
#set-window-option -g window-status-style dim

# active window title colors
set-window-option -g window-status-current-style fg=colour166,bg=default #orange and default
#set-window-option -g window-status-current-style bright

# pane border
set-option -g pane-border-style fg=colour235        #base02
set-option -g pane-active-border-style fg=colour240 #base01

# message text
set-option -g message-style fg=colour166,bg=colour235 #orange and base02

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166       #orange

# clock
set-window-option -g clock-mode-colour colour64 #green

# bell
set-window-option -g window-status-bell-style fg=colour235,bg=colour160 #base02, red
