# My TMUX Config

# ZSH as default TMUX shell
set-option -g default-shell /bin/zsh

# 256 term colors
set -g default-terminal "screen-256color"

# set pane-base index
set-option -g base-index 1
set-window-option -g pane-base-index 1
set-window-option -g mouse on

# set scroll-back history
set -g history-limit 10000

# set mouse support
set -g mouse on

# don't rename windows automatically
set-option -g allow-rename off

# decrease command delay
set -sg escape-time 1

# decrease escape timing for better scroll-buffer response
set -s escape-time 0

# remap prefix key from CTRL-b to CTRL-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using h(horizontal) and v(vertical)
bind v split-window -h -c'#{pane_current_path}'
bind h split-window -v -c'#{pane_current_path}'
unbind '"'
unbind %

# switch panes using ALT-arrow keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# resize panes
bind -r H resize-pane -L 5   # 5 px bigger to the left
bind -r J resize-pane -D 5   # 5 px bigger down
bind -r K resize-pane -U 5   # 5 px bigger up
bind -r L resize-pane -R 5   # 5 px bigger right

# Copy bindings. Unbind Ctrl + a, [ to enter copy mode, and
# bind ESCAPE
unbind [
bind Escape copy-mode

# vi mode copy keys
# go to start point, press 'v' and start copying, select with
# arrows
# After text selection, just press 'y' (or the default ‘enter’
# key) to copy text
setw -g mode-keys vi
# Capital 'P' for paste
unbind p
bind P paste-buffer

# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# silent like a ninja
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

# online status
set -g status-right "Online: #{online_status} | %a %h-%d %H:%M "

# TPM path
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin "arcticicestudio/nord-tmux"

run '~/.config/tmux/plugins/tpm/tpm'

