# My TMUX Config

# ZSH as default TMUX shell
set-option -g default-shell /bin/zsh

# 256 term colors
set -g default-terminal "screen-256color"

# set pane-base index
set-option -g base-index 1
set-window-option -g pane-base-index 1
set-window-option -g mouse on

# set scroll-back history
set -g history-limit 10000

# set mouse support
set -g mouse on

# decrease command delay
set -sg escape-time 1

# decrease escape timing for better scroll-buffer response
set -s escape-time 0

# remap prefix key from CTRL-b to CTRL-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# split panes using h(horizontal) and v(vertical)
bind v split-window -h -c'#{pane_current_path}'
bind h split-window -v -c'#{pane_current_path}'
unbind '"'
unbind %

# switch panes using ALT-arrow keys
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Copy bindings. Unbind Ctrl + a, [ to enter copy mode, and
# bind ESCAPE
unbind [
bind Escape copy-mode

# vi mode copy keys
# go to start point, press 'v' and start copying, select with
# arrows
# After text selection, just press 'y' (or the default ‘enter’
# key) to copy text
setw -g mode-keys vi
# Capital 'P' for paste
unbind p
bind P paste-buffer

# Copy from TMUX buffer to system buffer
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "xclip -i -f -selection primary | xclip -i -selection clipboard"

# silent like a ninja
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity off
set -g bell-action none

#  modes
setw -g clock-mode-colour colour1
setw -g mode-style 'fg=colour1 bg=colour18 bold'

# panes
set -g pane-border-style bg=default
set -g pane-active-border-style bg=default,fg=colour2
set -g pane-border-style fg=colour240

# statusbar config
set -g status-justify "left"
set -g status-left-length "100"
set -g status "on"
set -g status-right-length "160"
set -g status-style none
set -g status-right-style none
set -g status-left-style none
set -g status-left "#[fg=colour45] #S"
set -g status-right "#[fg=colour247] %R - %d-%m-%Y"

setw -g window-status-style bg=default,fg=colour242,none
setw -g window-status-current-style bg=default,fg=colour242
setw -g window-status-activity-style fg=colour2,none
setw -g window-status-separator ""
setw -g window-status-format "#[fg=colour242,nobold,nounderscore,noitalics] #[fg=colour242] #I #W #[fg=colour0,nobold,nounderscore,noitalics]"
setw -g window-status-current-format "#[fg=colour0,nobold,nounderscore,noitalics] #[fg=colour9] #I #W #[fg=colour0,nobold,nounderscore,noitalics]"

# messages
set -g message-style bg=colour2,fg=colour0

